# Generated by Django 5.1.2 on 2024-12-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ta',
            name='sections',
            field=models.ManyToManyField(related_name='tas', to='TAScheduler.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='assigned_tas',
            field=models.ManyToManyField(related_name='assigned_sections', to='TAScheduler.ta'),
        ),
    ]
