# Generated by Django 5.1.2 on 2024-12-01 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructortocourse',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_assignments', to='TAScheduler.instructor'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='ta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_labs', to='TAScheduler.ta'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='ta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grading_lectures', to='TAScheduler.ta'),
        ),
    ]
