# Generated by Django 5.1.2 on 2024-11-24 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0004_remove_user_is_staff_remove_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='num_of_sections',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
